---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 5
language: en-uk
name: Finding The Way Home
description: A beautiful narrative written with the world's most elegant publishing
  platform. The story begins here.
short_url: jekyller.github.io/jasper/
google_analytics: UA-69281367-1
disqus: username
baseurl: "/jasper/"
permalink: "/:title"
plugins:
- jekyll-paginate
safe: false
lsi: false
username: jekyller
repo: jasper
branch: master
relative_source: "../jasper/"
destination: "../jasper-pages/"
production_url: https://jekyller.github.io/jasper/
source_url: https://github.com/jekyller/jasper/
exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- ".travis.yml"
- node_modules
- ".git"
